import type { NextPage } from "next";
import Head from "next/head";
import ART from "data/art.json";
import { useMemo, useState } from "react";
import ArtTab from "components/arttab";

const Home: NextPage = () => {
  const { data } = ART;
  const [filterParam, setFilterParam] = useState("");
  const filteredData = useMemo(() => data.filter(
    (d) => (d.title.toLowerCase().startsWith(filterParam.toLowerCase()) ||
    d.artist.toLowerCase().startsWith(filterParam.toLowerCase())) || 
    d.created_at.toLowerCase().startsWith(filterParam.toLowerCase())
  ), [data, filterParam]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto w-full max-w-screen-lg">
        <div className="w-full p-5 justify-center">
          {/* TODO: Show the 4 pieces of art along with their details */}
          <h1>Example App</h1>
          <form>
            {/* TODO: Filter art */}
            <input 
              type="search" 
              placeholder="Search…" 
              onChange={(e) => setFilterParam(e.target.value)}
              className="border w-full my-5 h-12 px-5 rounded-md" 
            />
          </form>
          <ul className="flex flex-wrap justify-left">
            {filteredData.map(art => (
              <ArtTab art={art} key={art.title} />
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
